baseURL: "https://mymistypath.com/"
theme: PaperMod
title: My Misty Path
paginate: 5

buildDrafts: false
buildExpired: false
buildFuture: false
enableEmoji: true
enableRobotsTXT: true

permalinks:
  posts: posts/:filename

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: Misty
  description: "Join me on my blog as I explore and share my random thoughts and learnings."
  images: ["images/og.png"]
  title: My Misty Path
  comments: false
  disableScrollToTop: true
  hideFooter: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  defaultTheme: light
  showToc: false

  assets:
    disableHLJS: true
    favicon: "/images/favicon.svg"
    apple_touch_icon: "/images/favicon.svg"
    safari_pinned_tab: "/images/favicon.svg"

languages:
    en:
        languageName: "English"
        languageAltTitle: English
        weight: 1
        taxonomies:
          post: posts
        menu:
            main:
                - name: Posts
                  url: /posts/
                  weight: 10
                - name: About
                  url: /about
                  weight: 20
        profileMode:
            enabled: true
            title: "Misty Zhang"
            subtitle: "ğŸ¨ Interior Designer | ğŸ’ Florist | â€ğŸ’¡ Practitioner | â˜ï¸ Daydreamer"
            imageUrl: "/images/avatar.webp"
            imageWidth: 120
            imageHeight: 120
            imageTitle: avatar
        socialIcons:
        - name: "houzz"
          url: "https://www.houzz.com.au/pro/mistyz789"
        - name: "instagram"
          url: "https://www.instagram.com/misty_leileilei/"
        - name: "rss"
          url: "/index.xml"

    zh:
        languageName: "ä¸­æ–‡"
        languageAltTitle: ä¸­æ–‡
        weight: 2
        title: My Misty Path
        taxonomies:
          post: ZHposts

        menu:
          main:
            - identifier: posts
              name: æ–‡ç« 
              url: /posts/
              weight: 10
            - identifier: about
              name: å…³äº
              url: /about
              weight: 20
        profileMode:
            enabled: true
            title: "Misty Zhang"
            subtitle: "ç‚¹æ»´æ—¶åˆ»ï¼Œå¶ç„¶å‘ç”Ÿï¼Œäº›è®¸æ€åº¦ã€‚"
            imageUrl: "/images/avatar.webp"
            imageWidth: 120
            imageHeight: 120
            imageTitle: avatar
        socialIcons:
        - name: "houzz"
          url: "https://www.houzz.com.au/pro/mistyz789"
        - name: "instagram"
          url: "https://www.instagram.com/misty_leileilei/"
        - name: "rss"
          url: "/index.xml"


privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true

  youtube:
    privacyEnhanced: true
